sudo: required
servies:
  - docker

before_install:
  - docker build -t abhibhat97/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abhibhat97/react-test npm run test

after_success:
    - docker build -t abhibhat97/multi-client ./client
    - docker build -t abhibhat97/multi-nginx ./nginx
    - docker build -t abhibhat97/multi-server ./server
    - docker build -t abhibhat97/multi-worker ./worker
  deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "test-docker"
  env: "TestDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-730058774163"
  bucket_path: "test-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY