sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t abhibhat97/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run abhibhat97/react-test npm test -- --coverage

after_success:
  - docker build -t abhibhat97/multi-client ./client
  - docker build -t abhibhat97/multi-nginx ./nginx
  - docker build -t abhibhat97/multi-server ./server
  - docker build -t abhibhat97/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push abhibhat97/multi-client
  - docker push abhibhat97/multi-nginx
  - docker push abhibhat97/multi-server
  - docker push abhibhat97/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-730058774163'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
